// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHe5dCMsN-d4vdcerIeJ8mSRT3LHIo4lM',
    appId: '1:710849023513:web:3c79be815d0d24b776e488',
    messagingSenderId: '710849023513',
    projectId: 'carebot-d0a6b',
    authDomain: 'carebot-d0a6b.firebaseapp.com',
    storageBucket: 'carebot-d0a6b.appspot.com',
    measurementId: 'G-F6F37HZN5Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwA-NKhGJVJZ0Os5mVksngYN-Y0xGUWbc',
    appId: '1:710849023513:android:4dfa4918039546fe76e488',
    messagingSenderId: '710849023513',
    projectId: 'carebot-d0a6b',
    storageBucket: 'carebot-d0a6b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDP8alJLGfCIfLvclGEUdsRY5ukmYin-iE',
    appId: '1:710849023513:ios:b4ada0aab2d8358a76e488',
    messagingSenderId: '710849023513',
    projectId: 'carebot-d0a6b',
    storageBucket: 'carebot-d0a6b.appspot.com',
    iosBundleId: 'com.example.myapps',
  );

}